// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: auth.rpc.proto

package server

import (
	"context"

	"bookstore/rpc/auth/auth"
	"bookstore/rpc/auth/internal/logic"
	"bookstore/rpc/auth/internal/svc"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	auth.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServer) Login(ctx context.Context, in *auth.LoginReq) (*auth.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AuthServer) Register(ctx context.Context, in *auth.RegisterReq) (*auth.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}
