// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package adminuserservice

import (
	"context"

	"bookstore/rpc/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty           = user.Empty
	GetUserInfoReq  = user.GetUserInfoReq
	GetUserInfoResp = user.GetUserInfoResp
	UserInfo        = user.UserInfo
	UserInfoReq     = user.UserInfoReq
	UserListReq     = user.UserListReq
	UserListResp    = user.UserListResp
	UserUpdateReq   = user.UserUpdateReq

	AdminUserService interface {
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error)
		AddUser(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*UserInfo, error)
		UpdateUser(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*UserInfo, error)
		DeleteUser(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultAdminUserService struct {
		cli zrpc.Client
	}
)

func NewAdminUserService(cli zrpc.Client) AdminUserService {
	return &defaultAdminUserService{
		cli: cli,
	}
}

func (m *defaultAdminUserService) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := user.NewAdminUserServiceClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultAdminUserService) UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	client := user.NewAdminUserServiceClient(m.cli.Conn())
	return client.UserList(ctx, in, opts...)
}

func (m *defaultAdminUserService) AddUser(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*UserInfo, error) {
	client := user.NewAdminUserServiceClient(m.cli.Conn())
	return client.AddUser(ctx, in, opts...)
}

func (m *defaultAdminUserService) UpdateUser(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*UserInfo, error) {
	client := user.NewAdminUserServiceClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultAdminUserService) DeleteUser(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*Empty, error) {
	client := user.NewAdminUserServiceClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}
