// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "bookstore/admin/internal/handler/auth"
	permission "bookstore/admin/internal/handler/permission"
	user "bookstore/admin/internal/handler/user"
	"bookstore/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 登录
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.AuthLoginHandler(serverCtx),
			},
			{
				// 退出登录
				Method:  http.MethodPost,
				Path:    "/auth/logout",
				Handler: auth.AuthLogoutHandler(serverCtx),
			},
			{
				// 注册
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: auth.AuthRegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.PermissionMiddleware},
			[]rest.Route{
				{
					// 权限列表
					Method:  http.MethodGet,
					Path:    "/permission/list",
					Handler: permission.PermissionListHandler(serverCtx),
				},
				{
					// 添加角色
					Method:  http.MethodPost,
					Path:    "/permission/role/add",
					Handler: permission.AddRoleHandler(serverCtx),
				},
				{
					// 删除角色
					Method:  http.MethodDelete,
					Path:    "/permission/role/delete",
					Handler: permission.DeleteRoleHandler(serverCtx),
				},
				{
					// 获取角色信息
					Method:  http.MethodGet,
					Path:    "/permission/role/info",
					Handler: permission.GetRoleInfoHandler(serverCtx),
				},
				{
					// 角色列表
					Method:  http.MethodGet,
					Path:    "/permission/role/list",
					Handler: permission.RoleListHandler(serverCtx),
				},
				{
					// 更新角色
					Method:  http.MethodPost,
					Path:    "/permission/role/update",
					Handler: permission.UpdateRoleHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.PermissionMiddleware},
			[]rest.Route{
				{
					// 添加用户
					Method:  http.MethodPost,
					Path:    "/user/add",
					Handler: user.AddUserHandler(serverCtx),
				},
				{
					// 删除用户
					Method:  http.MethodDelete,
					Path:    "/user/delete",
					Handler: user.DeleteUserHandler(serverCtx),
				},
				{
					// 获取用户信息
					Method:  http.MethodGet,
					Path:    "/user/info",
					Handler: user.GetUserInfoHandler(serverCtx),
				},
				{
					// 用户列表
					Method:  http.MethodGet,
					Path:    "/user/list",
					Handler: user.UserListHandler(serverCtx),
				},
				{
					// 更新用户
					Method:  http.MethodPost,
					Path:    "/user/update",
					Handler: user.UpdateUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)
}
