// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "bookstore/admin/internal/handler/auth"
	user "bookstore/admin/internal/handler/user"
	"bookstore/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 登录
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.AuthLoginHandler(serverCtx),
			},
			{
				// 权限列表
				Method:  http.MethodGet,
				Path:    "/auth/permission/list",
				Handler: auth.PermissionListHandler(serverCtx),
			},
			{
				// 注册
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: auth.AuthRegisterHandler(serverCtx),
			},
			{
				// 添加角色
				Method:  http.MethodPost,
				Path:    "/auth/role/add",
				Handler: auth.AddRoleHandler(serverCtx),
			},
			{
				// 删除角色
				Method:  http.MethodDelete,
				Path:    "/auth/role/delete",
				Handler: auth.DeleteRoleHandler(serverCtx),
			},
			{
				// 获取角色信息
				Method:  http.MethodGet,
				Path:    "/auth/role/info",
				Handler: auth.GetRoleInfoHandler(serverCtx),
			},
			{
				// 角色列表
				Method:  http.MethodGet,
				Path:    "/auth/role/list",
				Handler: auth.RoleListHandler(serverCtx),
			},
			{
				// 更新角色
				Method:  http.MethodPost,
				Path:    "/auth/role/update",
				Handler: auth.UpdateRoleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.PermissionMiddleware},
			[]rest.Route{
				{
					// 获取用户信息
					Method:  http.MethodGet,
					Path:    "/user/info",
					Handler: user.GetUserInfoHandler(serverCtx),
				},
				{
					// 用户列表
					Method:  http.MethodGet,
					Path:    "/user/list",
					Handler: user.UserListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)
}
