version: "3.8"

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: bookstore-api
    ports:
      - "8888:8888"
    depends_on:
      - etcd
      - mysql
      - add-rpc-service
      - check-rpc-service
    networks:
      - bookstore-net
    volumes:
      - ./logs/api:/root/logs

  add-rpc-service:
    build:
      context: .
      dockerfile: Dockerfile.add-rpc
    container_name: bookstore-add-rpc
    ports:
      - "8080:8080"
    depends_on:
      - etcd
      - mysql
    networks:
      - bookstore-net
    volumes:
      - ./logs/add-rpc:/root/logs
    restart: always

  check-rpc-service:
    build:
      context: .
      dockerfile: Dockerfile.check-rpc
    container_name: bookstore-check-rpc
    ports:
      - "8081:8081"
    depends_on:
      - etcd
      - mysql
    networks:
      - bookstore-net
    volumes:
      - ./logs/check-rpc:/root/logs
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: gozero
    ports:
      - "3306:3306"
    volumes:
      - ./rpc/model/book.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - bookstore-net
    restart: always

  etcd:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd0 # 对应 --name
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379 # 对应 --listen-client-urls
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379 # 对应 --advertise-client-urls
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380 # 对应 --listen-peer-urls
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380 # 对应 --initial-advertise-peer-urls
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1 # 对应 --initial-cluster-token
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd:2380 # 对应 --initial-cluster
      - ETCD_INITIAL_CLUSTER_STATE=new # 对应 --initial-cluster-state
    ports:
      - "2379:2379"
    networks:
      - bookstore-net
    volumes:
      - etcd_data:/bitnami/etcd/data
    restart: always

  etcdkeeper:
    image: evildecay/etcdkeeper:latest # EtcdKeeper 官方 Docker 镜像
    container_name: etcdkeeper
    ports:
      - "8080:8999" # 将 EtcdKeeper 容器的 8080 端口映射到宿主机的 8080 端口
    environment:
      # 配置 EtcdKeeper 连接的 etcd 地址。
      # 这里的 "etcd" 是你的 etcd 服务在 Docker Compose 网络中的名称。
      ETCD_URLS: "http://etcd:2379"
      # ETCD_USERNAME: "your_username" # 如果 etcd 开启了认证
      # ETCD_PASSWORD: "your_password" # 如果 etcd 开启了认证
    depends_on:
      - etcd # 确保 etcd 服务启动后 EtcdKeeper 再启动
    networks:
      - bookstore-net
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411 # 用于Zipkin兼容性
      - COLLECTOR_OTLP_ENABLED=true # 启用OTLP接收，Go-Zero通常使用HTTP Thrift
    ports:
      - "6831:6831/udp" # Jaeger Agent 接收 Thrift TChannel UDP
      - "14268:14268" # Jaeger Collector HTTP 接收端口 (Go-Zero 配置的 Endpoint)
      - "14250:14250" # Jaeger Collector gRPC 接收端口
      - "16686:16686" # Jaeger UI 端口
      - "9411:9411" # Zipkin 兼容性端口
    networks:
      - bookstore-net
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml" # 指定配置文件路径
      - "--storage.tsdb.path=/prometheus" # 指定数据存储路径
    ports:
      - "9090:9090"
    networks:
      - bookstore-net
    depends_on:
      - api-service
      - add-rpc-service
      - check-rpc-service
    restart: always

networks:
  bookstore-net:
    driver: bridge

volumes:
  mysql_data:
  etcd_data:
  prometheus_data:
