# Dockerfile.api
FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o api-service ./api/bookstore.go

FROM alpine:latest

RUN apk add --no-cache ca-certificates

WORKDIR /root/
COPY --from=builder /app/api-service .

COPY --from=builder /app/api/etc/bookstore-api.yaml ./etc/bookstore-api.yaml

EXPOSE 8888
CMD ["./api-service", "-f", "./etc/bookstore-api.yaml"]
