# Dockerfile.add-rpc
FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o add-rpc-service ./rpc/add/add.go

FROM alpine:latest

RUN apk add --no-cache ca-certificates

WORKDIR /root/
COPY --from=builder /app/add-rpc-service .

COPY --from=builder /app/rpc/add/etc/add.yaml ./etc/add.yaml

EXPOSE 8080
CMD ["./add-rpc-service", "-f", "./etc/add.yaml"]

