version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - etcd
    networks:
      - bookstore-net

  add:
    build:
      context: ./rpc/add
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - etcd
      - mysql
    networks:
      - bookstore-net

  check:
    build:
      context: ./rpc/check
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - etcd
      - mysql
    networks:
      - bookstore-net

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: gozero
    ports:
      - "3306:3306"
    volumes:
      - ./rpc/model/book.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bookstore-net

  etcd:
    image: bitnami/etcd:3.4
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
    networks:
      - bookstore-net

networks:
  bookstore-net:
    driver: bridge
