# Dockerfile.check-rpc
FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o check-rpc-service ./rpc/check/check.go

FROM alpine:latest

RUN apk add --no-cache ca-certificates

WORKDIR /root/
COPY --from=builder /app/check-rpc-service .

COPY --from=builder /app/rpc/check/etc/check.yaml ./etc/check.yaml

EXPOSE 8081
CMD ["./check-rpc-service", "-f", "./etc/check.yaml"]

