# Dockerfile.add-rpc
FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o user-api-service ./rpc/user/user.go

FROM alpine:latest

RUN apk add --no-cache ca-certificates

WORKDIR /root/
COPY --from=builder /app/user-api-service .

COPY --from=builder /app/rpc/user/etc/user.api.yaml ./etc/user.api.yaml

EXPOSE 8281
CMD ["./user-api-service", "-f", "./etc/user.api.yaml"]


