// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: user.proto

package server

import (
	"context"

	"bookstore/rpc/user/internal/logic"
	"bookstore/rpc/user/internal/svc"
	"bookstore/rpc/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUserInfo(ctx context.Context, in *user.GetUserInfoReq) (*user.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserServer) UserList(ctx context.Context, in *user.UserListReq) (*user.UserListResp, error) {
	l := logic.NewUserListLogic(ctx, s.svcCtx)
	return l.UserList(in)
}
