// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: auth.rpc.proto

package server

import (
	"context"

	"bookstore/rpc/auth/auth"
	"bookstore/rpc/auth/internal/logic/apiauthservice"
	"bookstore/rpc/auth/internal/svc"
)

type ApiAuthServiceServer struct {
	svcCtx *svc.ServiceContext
	auth.UnimplementedApiAuthServiceServer
}

func NewApiAuthServiceServer(svcCtx *svc.ServiceContext) *ApiAuthServiceServer {
	return &ApiAuthServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ApiAuthServiceServer) Login(ctx context.Context, in *auth.LoginReq) (*auth.LoginResp, error) {
	l := apiauthservicelogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *ApiAuthServiceServer) Register(ctx context.Context, in *auth.RegisterReq) (*auth.RegisterResp, error) {
	l := apiauthservicelogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}
