// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type GetUserInfoResp struct {
	UserInfo
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string   `json:"token"`
	User  UserInfo `json:"user"`
}

type RegisterReq struct {
	Username         string `json:"username"`
	Password         string `json:"password"`
	Confirm_password string `json:"confirm_password"`
}

type RegisterResp struct {
	Token string   `json:"token"`
	User  UserInfo `json:"user"`
}

type UserInfo struct {
	Id        int64  `json:"id"`
	UserName  string `json:"username"`
	NickName  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Status    int    `json:"status"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type UserListReq struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`
}

type UserListResp struct {
	Total int64      `json:"total"`
	List  []UserInfo `json:"list"`
}
