// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type GetUserInfoResp struct {
	UserInfo
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type PageReq struct {
	Page     int64 `form:"page"`
	PageSize int64 `form:"pageSize"`
}

type Permission struct {
	Id          int64        `json:"id"`          // 权限ID
	Code        int          `json:"code"`        // 资源编码
	Description string       `json:"description"` // 权限描述
	ParentCode  int          `json:"parent_code"` // 父级资源编码
	Children    []Permission `json:"children"`    // 子资源
	CreatedAt   int64        `json:"created_at"`
	UpdatedAt   int64        `json:"updated_at"`
}

type RegisterReq struct {
	Username         string `json:"username"`
	Password         string `json:"password"`
	Confirm_password string `json:"confirm_password"`
}

type RegisterResp struct {
	Token string `json:"token"`
}

type Role struct {
	Id          int64        `json:"id"`
	Name        string       `json:"name"`
	Permissions []Permission `json:"permissions"`
	CreatedAt   int64        `json:"created_at"`
	UpdatedAt   int64        `json:"updated_at"`
}

type RoleInfoReq struct {
	Id int64 `path:"id"`
}

type RoleListResp struct {
	Total int64  `json:"total"`
	List  []Role `json:"list"`
}

type UserInfo struct {
	Id        int64  `json:"id"`
	UserName  string `json:"username"`
	NickName  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Status    int    `json:"status"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type UserListResp struct {
	Total int64      `json:"total"`
	List  []UserInfo `json:"list"`
}
