// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetUserInfoResp struct {
	UserInfo
}

type LoginReq struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 密码
}

type LoginResp struct {
	Token string `json:"token"`
}

type PageReq struct {
	Page     int64 `form:"page"`
	PageSize int64 `form:"pageSize"`
}

type Permission struct {
	Id          int64        `json:"id"`          // 权限ID
	Code        int          `json:"code"`        // 资源编码
	Description string       `json:"description"` // 权限描述
	ParentCode  int          `json:"parent_code"` // 父级资源编码
	Children    []Permission `json:"children"`    // 子资源
	CreatedAt   int64        `json:"created_at"`
	UpdatedAt   int64        `json:"updated_at"`
}

type RegisterReq struct {
	Username         string `json:"username"`
	Password         string `json:"password"`
	Confirm_password string `json:"confirm_password"`
	RoleId           int64  `json:"role_id"`
}

type RegisterResp struct {
	Token string `json:"token"`
}

type Role struct {
	Id          int64        `json:"id"`          // 角色ID
	Name        string       `json:"name"`        // 角色名
	Permissions []Permission `json:"permissions"` // 权限
	Status      int          `json:"status"`      // 状态
	CreatedAt   int64        `json:"created_at"`  // 创建时间
	UpdatedAt   int64        `json:"updated_at"`  // 更新时间
}

type RoleInfoReq struct {
	Id int64 `path:"id"` // 角色ID
}

type RoleListResp struct {
	Total int64  `json:"total"` // 总数
	List  []Role `json:"list"`  // 列表
}

type RolePermission struct {
	RoleId         int64  `json:"role_id"`         // 角色ID
	RoleName       string `json:"role_name"`       // 角色名
	PermissionId   int64  `json:"permission_id"`   // 权限ID
	PermissionName string `json:"permission_name"` // 权限名
}

type UserInfo struct {
	Id        int64            `json:"id"`         // 用户ID
	UserName  string           `json:"username"`   // 用户名
	NickName  string           `json:"nickname"`   // 昵称
	Avatar    string           `json:"avatar"`     // 头像
	Email     string           `json:"email"`      // 邮箱
	Phone     string           `json:"phone"`      // 手机号
	Roles     []RolePermission `json:"roles"`      // 角色
	Status    int              `json:"status"`     // 状态
	CreatedAt int64            `json:"created_at"` // 创建时间
	UpdatedAt int64            `json:"updated_at"` // 更新时间
}

type UserListResp struct {
	Total int64      `json:"total"`
	List  []UserInfo `json:"list"`
}
