// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tRoleFieldNames          = builder.RawFieldNames(&TRole{}, true)
	tRoleRows                = strings.Join(tRoleFieldNames, ",")
	tRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(tRoleFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	tRoleRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(tRoleFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	tRoleModel interface {
		Insert(ctx context.Context, data *TRole) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TRole, error)
		FindOneByName(ctx context.Context, name string) (*TRole, error)
		Update(ctx context.Context, data *TRole) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTRoleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TRole struct {
		Id        int64     `db:"id"`         // 角色ID
		Name      string    `db:"name"`       // 角色名
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
		Status    int64     `db:"status"`
	}
)

func newTRoleModel(conn sqlx.SqlConn) *defaultTRoleModel {
	return &defaultTRoleModel{
		conn:  conn,
		table: `"public"."t_role"`,
	}
}

func (m *defaultTRoleModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTRoleModel) FindOne(ctx context.Context, id int64) (*TRole, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", tRoleRows, m.table)
	var resp TRole
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTRoleModel) FindOneByName(ctx context.Context, name string) (*TRole, error) {
	var resp TRole
	query := fmt.Sprintf("select %s from %s where name = $1 limit 1", tRoleRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTRoleModel) Insert(ctx context.Context, data *TRole) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, tRoleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Status)
	return ret, err
}

func (m *defaultTRoleModel) Update(ctx context.Context, newData *TRole) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, tRoleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.Name, newData.Status)
	return err
}

func (m *defaultTRoleModel) tableName() string {
	return m.table
}
