// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.4

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tUserFieldNames          = builder.RawFieldNames(&TUser{}, true)
	tUserRows                = strings.Join(tUserFieldNames, ",")
	tUserRowsExpectAutoSet   = strings.Join(stringx.Remove(tUserFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	tUserRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(tUserFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	tUserModel interface {
		Insert(ctx context.Context, data *TUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TUser, error)
		FindOneByUsername(ctx context.Context, username string) (*TUser, error)
		FindOneByUsernameAndPassword(ctx context.Context, username, password string) (*TUser, error)
		FindAllByPage(ctx context.Context, page, pageSize int64) (*[]TUser, error)
		Count(ctx context.Context) (int64, error)
		Update(ctx context.Context, data *TUser) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TUser struct {
		Id        int64     `db:"id"`         // 用户ID
		Username  string    `db:"username"`   // 用户名
		Password  string    `db:"password"`   // 密码hash
		Nickname  string    `db:"nickname"`   // 昵称
		Avatar    string    `db:"avatar"`     // 头像
		Email     string    `db:"email"`      // 邮箱
		Phone     string    `db:"phone"`      // 手机号
		Status    int64     `db:"status"`     // 状态(1:正常 0:禁用)
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newTUserModel(conn sqlx.SqlConn) *defaultTUserModel {
	return &defaultTUserModel{
		conn:  conn,
		table: `"public"."t_user"`,
	}
}

func (m *defaultTUserModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTUserModel) FindOne(ctx context.Context, id int64) (*TUser, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", tUserRows, m.table)
	var resp TUser
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTUserModel) FindOneByUsername(ctx context.Context, username string) (*TUser, error) {
	var resp TUser
	query := fmt.Sprintf("select %s from %s where username = $1 limit 1", tUserRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, username)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTUserModel) FindOneByUsernameAndPassword(ctx context.Context, username, password string) (*TUser, error) {
	var resp TUser
	query := fmt.Sprintf("select %s from %s where username = $1 and password = $2 limit 1", tUserRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, username, password)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTUserModel) FindAllByPage(ctx context.Context, page, pageSize int64) (*[]TUser, error) {
	query := fmt.Sprintf("select %s from %s limit $1 offset $2", tUserRows, m.table)
	var resp []TUser
	err := m.conn.QueryRowsCtx(ctx, &resp, query, pageSize, (page-1)*pageSize)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTUserModel) Count(ctx context.Context) (int64, error) {
	query := fmt.Sprintf("select count(1) from %s", m.table)
	var resp int64
	err := m.conn.QueryRowCtx(ctx, &resp, query)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultTUserModel) Insert(ctx context.Context, data *TUser) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7)", m.table, tUserRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Username, data.Password, data.Nickname, data.Avatar, data.Email, data.Phone, data.Status)
	return ret, err
}

func (m *defaultTUserModel) Update(ctx context.Context, newData *TUser) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, tUserRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.Username, newData.Password, newData.Nickname, newData.Avatar, newData.Email, newData.Phone, newData.Status)
	return err
}

func (m *defaultTUserModel) tableName() string {
	return m.table
}
