// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.4

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tRolePermissionFieldNames          = builder.RawFieldNames(&TRolePermission{}, true)
	tRolePermissionRows                = strings.Join(tRolePermissionFieldNames, ",")
	tRolePermissionRowsExpectAutoSet   = strings.Join(stringx.Remove(tRolePermissionFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	tRolePermissionRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(tRolePermissionFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	tRolePermissionModel interface {
		Insert(ctx context.Context, data *TRolePermission) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TRolePermission, error)
		FindOneByRoleIdPermissionId(ctx context.Context, roleId int64, permissionId int64) (*TRolePermission, error)
		Update(ctx context.Context, data *TRolePermission) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTRolePermissionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TRolePermission struct {
		Id           int64     `db:"id"`            // 角色权限ID
		RoleId       int64     `db:"role_id"`       // 角色ID
		PermissionId int64     `db:"permission_id"` // 权限ID
		CreatedAt    time.Time `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time `db:"updated_at"`    // 更新时间
	}
)

func newTRolePermissionModel(conn sqlx.SqlConn) *defaultTRolePermissionModel {
	return &defaultTRolePermissionModel{
		conn:  conn,
		table: `"public"."t_role_permission"`,
	}
}

func (m *defaultTRolePermissionModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTRolePermissionModel) FindOne(ctx context.Context, id int64) (*TRolePermission, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", tRolePermissionRows, m.table)
	var resp TRolePermission
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTRolePermissionModel) FindOneByRoleIdPermissionId(ctx context.Context, roleId int64, permissionId int64) (*TRolePermission, error) {
	var resp TRolePermission
	query := fmt.Sprintf("select %s from %s where role_id = $1 and permission_id = $2 limit 1", tRolePermissionRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, roleId, permissionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTRolePermissionModel) Insert(ctx context.Context, data *TRolePermission) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, tRolePermissionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RoleId, data.PermissionId)
	return ret, err
}

func (m *defaultTRolePermissionModel) Update(ctx context.Context, newData *TRolePermission) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, tRolePermissionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.RoleId, newData.PermissionId)
	return err
}

func (m *defaultTRolePermissionModel) tableName() string {
	return m.table
}
