// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: auth.rpc.proto

package apiauthservice

import (
	"context"

	"bookstore/rpc/auth/auth"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty              = auth.Empty
	LoginReq           = auth.LoginReq
	LoginResp          = auth.LoginResp
	PageReq            = auth.PageReq
	Permission         = auth.Permission
	PermissionListReq  = auth.PermissionListReq
	PermissionListResp = auth.PermissionListResp
	RegisterReq        = auth.RegisterReq
	RegisterResp       = auth.RegisterResp
	Role               = auth.Role
	RoleInfoReq        = auth.RoleInfoReq
	RoleListResp       = auth.RoleListResp

	ApiAuthService interface {
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	}

	defaultApiAuthService struct {
		cli zrpc.Client
	}
)

func NewApiAuthService(cli zrpc.Client) ApiAuthService {
	return &defaultApiAuthService{
		cli: cli,
	}
}

func (m *defaultApiAuthService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := auth.NewApiAuthServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultApiAuthService) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := auth.NewApiAuthServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}
