// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: auth.rpc.proto

package server

import (
	"context"

	"bookstore/rpc/auth/auth"
	"bookstore/rpc/auth/internal/logic/adminauthservice"
	"bookstore/rpc/auth/internal/svc"
)

type AdminAuthServiceServer struct {
	svcCtx *svc.ServiceContext
	auth.UnimplementedAdminAuthServiceServer
}

func NewAdminAuthServiceServer(svcCtx *svc.ServiceContext) *AdminAuthServiceServer {
	return &AdminAuthServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AdminAuthServiceServer) Login(ctx context.Context, in *auth.LoginReq) (*auth.LoginResp, error) {
	l := adminauthservicelogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AdminAuthServiceServer) Register(ctx context.Context, in *auth.RegisterReq) (*auth.RegisterResp, error) {
	l := adminauthservicelogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *AdminAuthServiceServer) PermissionList(ctx context.Context, in *auth.PermissionListReq) (*auth.PermissionListResp, error) {
	l := adminauthservicelogic.NewPermissionListLogic(ctx, s.svcCtx)
	return l.PermissionList(in)
}

func (s *AdminAuthServiceServer) AddRole(ctx context.Context, in *auth.Role) (*auth.Empty, error) {
	l := adminauthservicelogic.NewAddRoleLogic(ctx, s.svcCtx)
	return l.AddRole(in)
}

func (s *AdminAuthServiceServer) UpdateRole(ctx context.Context, in *auth.Role) (*auth.Empty, error) {
	l := adminauthservicelogic.NewUpdateRoleLogic(ctx, s.svcCtx)
	return l.UpdateRole(in)
}

func (s *AdminAuthServiceServer) RoleList(ctx context.Context, in *auth.PageReq) (*auth.RoleListResp, error) {
	l := adminauthservicelogic.NewRoleListLogic(ctx, s.svcCtx)
	return l.RoleList(in)
}

func (s *AdminAuthServiceServer) GetRoleInfo(ctx context.Context, in *auth.RoleInfoReq) (*auth.Role, error) {
	l := adminauthservicelogic.NewGetRoleInfoLogic(ctx, s.svcCtx)
	return l.GetRoleInfo(in)
}

func (s *AdminAuthServiceServer) DeleteRole(ctx context.Context, in *auth.RoleInfoReq) (*auth.Empty, error) {
	l := adminauthservicelogic.NewDeleteRoleLogic(ctx, s.svcCtx)
	return l.DeleteRole(in)
}
