// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: auth.rpc.proto

package server

import (
	"context"

	"bookstore/rpc/auth/auth"
	"bookstore/rpc/auth/internal/logic/adminauthservice"
	"bookstore/rpc/auth/internal/svc"
)

type AdminAuthServiceServer struct {
	svcCtx *svc.ServiceContext
	auth.UnimplementedAdminAuthServiceServer
}

func NewAdminAuthServiceServer(svcCtx *svc.ServiceContext) *AdminAuthServiceServer {
	return &AdminAuthServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AdminAuthServiceServer) Login(ctx context.Context, in *auth.LoginReq) (*auth.LoginResp, error) {
	l := adminauthservicelogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AdminAuthServiceServer) Register(ctx context.Context, in *auth.RegisterReq) (*auth.RegisterResp, error) {
	l := adminauthservicelogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}
